### ISSUE TITLE
Update base58 to 2.0.0

### ISSUE THREAD

**Issue by fubuloubu** [ipld/py-cid#27]
### Description
This package is pinned to assume base58 < 2.0.0

**Comment by CMCDragonkai** [comment]
Is this package compatible with base58 2.0.1?

**Comment by al2m4n** [comment]
> Is this package compatible with base58 2.0.1?

Same question here. Why is it pinned to < 2.0.0? , there are dependency conflicts in my project then.

**Comment by BigLep** [comment]
Per https://github.com/ipld/py-cid/blob/master/README.rst, this repo is not maintained and been archived.

If someone would like to fork it and support it, IPLD stewards are happy to point to a supported fork. Please open an issue in ipld/ipld requesting this ofrask in #ipld in IPFS Discod, Matrix, or FIL Slack.

**Comment by rvagg** [comment]
repo is being (re)archived

**Comment by fubuloubu** [comment]
Seems like it was un-(re)archived (or at least there's been several releases in the past year), can this issue be re-opened?

More than happy to provide the patch
