### ISSUE TITLE
Add references for codecs and encodings supported via multicodec and multibase in the documentation

### ISSUE THREAD

**Issue by dhruvbaldawa** [ipld/py-cid#3]

**Comment by BigLep** [comment]
Per https://github.com/ipld/py-cid/blob/master/README.rst, this repo is not maintained and been archived.

If someone would like to fork it and support it, IPLD stewards are happy to point to a supported fork. Please open an issue in ipld/ipld requesting this ofrask in #ipld in IPFS Discod, Matrix, or FIL Slack.

**Comment by rvagg** [comment]
repo is being (re)archived
